language: elixir
elixir:
  - 1.1.1
otp_release:
  - 18
sudo: false # to use faster container based build environment
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
services:
  - redis
notifications:
  recipients:
    - vitumail@gmail.com
