language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.3
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.0
      elixir: 1.4
    - otp_release: 20.0
      elixir: 1.5
sudo: false
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
services:
  - redis
